require 'securerandom'

module ForestAdminAgent
  module Http
    # Per-request correlation id, generated by the agent. Shared between the caller (so the audit
    # trail can group every change made within one request) and the response header echoed back to
    # the client. Mirrors the Node agent's `context.state.requestId` + `x-forest-correlation-id`
    # header: the agent generates the id, never reads it from the incoming request.
    #
    # Stored thread-locally and generated lazily on first read (e.g. when the caller is parsed). The
    # host resets it at the start of each request so a pooled thread never reuses a previous id.
    module CorrelationId
      HEADER = 'x-forest-correlation-id'.freeze
      KEY = :forest_admin_correlation_id

      module_function

      # Lazily generate and memoize the id for the current request/thread.
      def current
        Thread.current[KEY] ||= SecureRandom.uuid
      end

      # The id if one was generated during this request, otherwise nil (does not generate one).
      def current?
        Thread.current[KEY]
      end

      def current=(value)
        Thread.current[KEY] = value
      end

      def reset!
        Thread.current[KEY] = nil
      end
    end
  end
end
