version: "2"
plugins:
  rubocop:
    enabled: true
    channel: "rubocop-1-56-3"
    config:
      require:
        - rubocop-performance
        - rubocop-rspec
  test-reporter:
    formatter: simplecov
