version: "2"
plugins:
  rubocop:
    enabled: true
    channel: "rubocop-1-56-3"
    config:
      file: ".rubocop.yml"
#      require:
#        - rubocop-performance
#        - rubocop-rspec
  test-reporter:
    formatter: simplecov
prepare:
  steps:
    - run:
        name: Install RuboCop Performance and RSpec
        command: |
          gem install rubocop-performance
          gem install rubocop-rspec