CommitMsg:
  MessageFormat:
    enabled: true
    description: 'Check commit message matches expected pattern'
    pattern: '^(?<type>build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(?<scope>\(\w+\)?((?=:\s)|(?=!:\s)))?(?<breaking>!)?(?<subject>:\s.*)'
    expected_pattern_message: '<type>(<scope>): <subject>'
    sample_message: 'feat(datasource): add onboarding flow'

PreCommit:
  RuboCop:
    enabled: true
    description: 'Analyze with RuboCop'
    required_executable: 'rubocop'
    flags: ['--format=emacs', '--force-exclusion', '--display-cop-names']
    install_command: 'gem install rubocop'
    include:
      - '**/*.gemspec'
      - '**/*.rake'
      - '**/*.rb'
      - '**/*.ru'
      - '**/Gemfile'
      - '**/Rakefile'

  TrailingWhitespace:
    enabled: true
    #exclude:
    #  - '**/db/structure.sql' # Ignore trailing whitespace in generated files

  BundleOutdated:
    enabled: true

  BundleAudit:
    enabled: true

PrePush:
  RSpec:
    enabled: true
    command: ["run_rspec"]
    quiet: false
