require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'packages/forest_admin_datasource_active_record/spec/dummy/**/*'

Gemspec/OrderedDependencies:
  Exclude:
    - 'packages/forest_admin_agent/forest_admin_agent.gemspec'
    - 'packages/forest_admin_rails/forest_admin_rails.gemspec'
    - 'packages/forest_admin_datasource_toolkit/forest_admin_datasource_toolkit.gemspec'
    - 'packages/forest_admin_datasource_active_record/forest_admin_datasource_active_record.gemspec'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/PercentStringArray:
  Exclude:
    - 'packages/forest_admin_agent/forest_admin_agent.gemspec'
    - 'packages/forest_admin_rails/forest_admin_rails.gemspec'
    - 'packages/forest_admin_datasource_toolkit/forest_admin_datasource_toolkit.gemspec'
    - 'packages/forest_admin_datasource_active_record/forest_admin_datasource_active_record.gemspec'

# Offense count: 1
# Configuration parameters: AllowComments.
Lint/EmptyFile:
  Exclude:
    - 'packages/forest_admin_rails/app/models/forest_admin_rails/application_record.rb'

Metrics/AbcSize:
  Exclude:
    - 'packages/forest_admin_agent/lib/forest_admin_agent/auth/auth_manager.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/auth/oauth2/forest_provider.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/auth/oidc_client_manager.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/parser/validation.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_field.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/schema_emitter.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'packages/forest_admin_agent/lib/forest_admin_agent/auth/oauth2/forest_provider.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/parser/validation.rb'

Style/BlockComments:
  Exclude:
    - 'packages/forest_admin_agent/spec/spec_helper.rb'
    - 'packages/forest_admin_rails/spec/spec_helper.rb'
    - 'packages/forest_admin_datasource_toolkit/spec/spec_helper.rb'
    - 'packages/forest_admin_datasource_active_record/spec/spec_helper.rb'

# Offense count: 3
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Enabled: false

# Offense count: 9
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Exclude:
    - 'lib/agent_ruby/version.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/version.rb'
    - 'packages/forest_admin_rails/lib/forest_admin_rails/version.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/version.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/version.rb'

# Offense count: 38
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'agent_ruby.gemspec'
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/console'
    - 'lib/agent_ruby.rb'
    - 'lib/agent_ruby/version.rb'
    - 'packages/forest_admin_agent/forest_admin_agent.gemspec'
    - 'packages/forest_admin_agent/Gemfile'
    - 'packages/forest_admin_agent/Rakefile'
    - 'packages/forest_admin_agent/bin/console'
    - 'packages/forest_admin_agent/lib/forest_admin_agent.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/version.rb'
    - 'packages/forest_admin_agent/spec/forest_admin_agent_spec.rb'
    - 'packages/forest_admin_agent/spec/spec_helper.rb'
    - 'packages/forest_admin_rails/forest_admin_rails.gemspec'
    - 'packages/forest_admin_rails/Gemfile'
    - 'packages/forest_admin_rails/Rakefile'
    - 'packages/forest_admin_rails/bin/console'
    - 'packages/forest_admin_rails/bin/rails'
    - 'packages/forest_admin_rails/lib/forest_admin_rails.rb'
    - 'packages/forest_admin_rails/lib/forest_admin_rails/version.rb'
    - 'packages/forest_admin_rails/spec/rails_helper.rb'
    - 'packages/forest_admin_rails/spec/spec_helper.rb'
    - 'packages/forest_admin_datasource_toolkit/forest_admin_datasource_toolkit.gemspec'
    - 'packages/forest_admin_datasource_toolkit/Gemfile'
    - 'packages/forest_admin_datasource_toolkit/Rakefile'
    - 'packages/forest_admin_datasource_toolkit/bin/console'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/version.rb'
    - 'packages/forest_admin_datasource_toolkit/spec/spec_helper.rb'
    - 'packages/forest_admin_datasource_active_record/forest_admin_datasource_active_record.gemspec'
    - 'packages/forest_admin_datasource_active_record/Gemfile'
    - 'packages/forest_admin_datasource_active_record/Rakefile'
    - 'packages/forest_admin_datasource_active_record/bin/console'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/version.rb'
    - 'packages/forest_admin_datasource_active_record/spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 3

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/RedundantConstantBase:
  Exclude:
    - 'packages/forest_admin_rails/spec/rails_helper.rb'

Naming/PredicateName:
  Exclude:
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/collection.rb'

Metrics/ParameterLists:
  Exclude:
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/schema/relations/many_to_many_schema.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/schema/column_schema.rb'

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'method_call']
  Max: 20
  Exclude:
    - 'packages/forest_admin_agent/lib/forest_admin_agent/auth/oauth2/forest_provider.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/parser/validation.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb'
    - 'packages/forest_admin_datasource_active_record/spec/dummy/**/*'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/collection.rb'

Metrics/BlockLength:
  Exclude:
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/parser/validation.rb'

Metrics/ClassLength:
  Exclude:
    - 'packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_field.rb'

RSpec/ExampleLength:
  CountAsOne: [ 'array', 'hash', 'method_call' ]
  Max: 20


RSpec/MultipleExpectations:
  Max: 5

Layout/LineLength:
  Max: 120

RSpec/MultipleMemoizedHelpers:
  Max: 10
