require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Gemspec/OrderedDependencies:
  Exclude:
    - 'packages/forest_admin_agent/forest_admin_agent.gemspec'
    - 'packages/forest_admin_rails/forest_admin_rails.gemspec'
    - 'forest_admin_rails.gemspec'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/PercentStringArray:
  Exclude:
    - 'packages/forest_admin_agent/forest_admin_agent.gemspec'

# Offense count: 1
# Configuration parameters: AllowComments.
Lint/EmptyFile:
  Exclude:
    - 'packages/forest_admin_rails/app/models/forest_admin_rails/application_record.rb'

Style/BlockComments:
  Exclude:
    - 'packages/forest_admin_agent/spec/spec_helper.rb'
    - 'packages/forest_admin_rails/spec/spec_helper.rb'

# Offense count: 3
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Enabled: false

# Offense count: 9
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Exclude:
    - 'lib/agent_ruby/version.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/version.rb'
    - 'packages/forest_admin_rails/lib/forest_admin_rails/version.rb'

# Offense count: 38
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'agent_ruby.gemspec'
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/console'
    - 'lib/agent_ruby.rb'
    - 'lib/agent_ruby/version.rb'
    - 'packages/forest_admin_agent/forest_admin_agent.gemspec'
    - 'packages/forest_admin_agent/Gemfile'
    - 'packages/forest_admin_agent/Rakefile'
    - 'packages/forest_admin_agent/bin/console'
    - 'packages/forest_admin_agent/lib/forest_admin_agent.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/version.rb'
    - 'packages/forest_admin_agent/spec/forest_admin_agent_spec.rb'
    - 'packages/forest_admin_agent/spec/spec_helper.rb'
    - 'packages/forest_admin_rails/forest_admin_rails.gemspec'
    - 'packages/forest_admin_rails/Gemfile'
    - 'packages/forest_admin_rails/Rakefile'
    - 'packages/forest_admin_rails/bin/console'
    - 'packages/forest_admin_rails/bin/rails'
    - 'packages/forest_admin_rails/lib/forest_admin_rails.rb'
    - 'packages/forest_admin_rails/lib/forest_admin_rails/version.rb'
    - 'packages/forest_admin_rails/spec/rails_helper.rb'
    - 'packages/forest_admin_rails/spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 3

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/RedundantConstantBase:
  Exclude:
    - 'packages/forest_admin_rails/spec/rails_helper.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'packages/forest_admin_agent/lib/forest_admin_agent/utils/error_messages.rb'
