require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  Exclude:
    - 'packages/forest_admin_datasource_active_record/spec/dummy/**/*'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/serializer/forest_serializer.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/serializer/forest_serializer_override.rb'
    - 'node_modules/semantic-release-rubygem/**/*'

Gemspec/OrderedDependencies:
  Exclude:
    - 'packages/forest_admin_agent/forest_admin_agent.gemspec'
    - 'packages/forest_admin_rails/forest_admin_rails.gemspec'
    - 'packages/forest_admin_datasource_toolkit/forest_admin_datasource_toolkit.gemspec'
    - 'packages/forest_admin_datasource_customizer/forest_admin_datasource_customizer.gemspec'
    - 'packages/forest_admin_datasource_active_record/forest_admin_datasource_active_record.gemspec'

Gemspec/RequireMFA:
  Exclude:
    - 'agent_ruby.gemspec'
    - 'packages/forest_admin_agent/forest_admin_agent.gemspec'
    - 'packages/forest_admin_rails/forest_admin_rails.gemspec'
    - 'packages/forest_admin_datasource_toolkit/forest_admin_datasource_toolkit.gemspec'
    - 'packages/forest_admin_datasource_customizer/forest_admin_datasource_customizer.gemspec'
    - 'packages/forest_admin_datasource_active_record/forest_admin_datasource_active_record.gemspec'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/PercentStringArray:
  Exclude:
    - 'packages/forest_admin_agent/forest_admin_agent.gemspec'
    - 'packages/forest_admin_rails/forest_admin_rails.gemspec'
    - 'packages/forest_admin_datasource_toolkit/forest_admin_datasource_toolkit.gemspec'
    - 'packages/forest_admin_datasource_customizer/forest_admin_datasource_customizer.gemspec'
    - 'packages/forest_admin_datasource_active_record/forest_admin_datasource_active_record.gemspec'

# Offense count: 1
# Configuration parameters: AllowComments.
Lint/EmptyFile:
  Exclude:
    - 'packages/forest_admin_rails/app/models/forest_admin_rails/application_record.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/BlockComments:
  Exclude:
    - 'packages/forest_admin_agent/spec/spec_helper.rb'
    - 'packages/forest_admin_rails/spec/spec_helper.rb'
    - 'packages/forest_admin_datasource_toolkit/spec/spec_helper.rb'
    - 'packages/forest_admin_datasource_customizer/spec/spec_helper.rb'
    - 'packages/forest_admin_datasource_active_record/spec/spec_helper.rb'

# Offense count: 3
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Enabled: false

# Offense count: 9
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Exclude:
    - 'lib/agent_ruby/version.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/version.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/schema_emitter.rb'
    - 'packages/forest_admin_rails/lib/forest_admin_rails/version.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/version.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/version.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/version.rb'

# Offense count: 38
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'agent_ruby.gemspec'
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/console'
    - 'lib/agent_ruby.rb'
    - 'lib/agent_ruby/version.rb'
    - 'packages/forest_admin_agent/forest_admin_agent.gemspec'
    - 'packages/forest_admin_agent/Gemfile'
    - 'packages/forest_admin_agent/Rakefile'
    - 'packages/forest_admin_agent/bin/console'
    - 'packages/forest_admin_agent/lib/forest_admin_agent.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/version.rb'
    - 'packages/forest_admin_agent/spec/forest_admin_agent_spec.rb'
    - 'packages/forest_admin_agent/spec/spec_helper.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/schema_emitter.rb'
    - 'packages/forest_admin_rails/forest_admin_rails.gemspec'
    - 'packages/forest_admin_rails/Gemfile'
    - 'packages/forest_admin_rails/Rakefile'
    - 'packages/forest_admin_rails/bin/console'
    - 'packages/forest_admin_rails/bin/rails'
    - 'packages/forest_admin_rails/lib/forest_admin_rails.rb'
    - 'packages/forest_admin_rails/lib/forest_admin_rails/version.rb'
    - 'packages/forest_admin_rails/spec/rails_helper.rb'
    - 'packages/forest_admin_rails/spec/spec_helper.rb'
    - 'packages/forest_admin_datasource_toolkit/forest_admin_datasource_toolkit.gemspec'
    - 'packages/forest_admin_datasource_toolkit/Gemfile'
    - 'packages/forest_admin_datasource_toolkit/Rakefile'
    - 'packages/forest_admin_datasource_toolkit/bin/console'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/version.rb'
    - 'packages/forest_admin_datasource_toolkit/spec/spec_helper.rb'
    - 'packages/forest_admin_datasource_customizer/forest_admin_datasource_customizer.gemspec'
    - 'packages/forest_admin_datasource_customizer/Gemfile'
    - 'packages/forest_admin_datasource_customizer/Rakefile'
    - 'packages/forest_admin_datasource_customizer/bin/console'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/version.rb'
    - 'packages/forest_admin_datasource_customizer/spec/spec_helper.rb'
    - 'packages/forest_admin_datasource_active_record/forest_admin_datasource_active_record.gemspec'
    - 'packages/forest_admin_datasource_active_record/Gemfile'
    - 'packages/forest_admin_datasource_active_record/Rakefile'
    - 'packages/forest_admin_datasource_active_record/bin/console'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/version.rb'
    - 'packages/forest_admin_datasource_active_record/spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 3

Style/SymbolArray:
  Exclude:
    - 'packages/forest_admin_agent/spec/lib/forest_admin_agent/utils/schema/generator_field_many_to_many_spec.rb'

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/RedundantConstantBase:
  Exclude:
    - 'packages/forest_admin_rails/spec/rails_helper.rb'

Style/HashEachMethods:
  Exclude:
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/condition_tree/condition_tree_factory.rb'

Lint/NestedMethodDefinition:
  Exclude:
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/filter_factory.rb'

Performance/CollectionLiteralInLoop:
  Exclude:
    - 'packages/forest_admin_agent/lib/forest_admin_agent/utils/condition_tree_parser.rb'

Naming/PredicateName:
  Exclude:
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/collection.rb'

Metrics/ParameterLists:
  Exclude:
    - 'packages/forest_admin_agent/lib/forest_admin_agent/services/smart_action_checker.rb'
    - 'packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/related/list_related_spec.rb'
    - 'packages/forest_admin_agent/spec/lib/forest_admin_agent/routes/resources/related/count_related_spec.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/context/action_context.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/action_collection_decorator.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/dynamic_field.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/hook/context/after/hook_after_aggregate_context.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/schema/relations/many_to_many_schema.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/schema/column_schema.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/caller.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/filter.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/utils/collection.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/action_field.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/actions/action_field.rb'

Metrics/ModuleLength:
  CountAsOne: [ 'array', 'hash', 'method_call' ]
  Exclude:
    - 'packages/forest_admin_agent/spec/**/*'
    - 'packages/forest_admin_datasource_active_record/spec/**/*'
    - 'packages/forest_admin_datasource_toolkit/spec/**/*'
    - 'packages/forest_admin_datasource_customizer/spec/**/*'
    - 'packages/forest_admin_rails/spec/**/*'

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'method_call']
  Max: 20
  Exclude:
    - 'packages/forest_admin_agent/lib/forest_admin_agent/auth/oauth2/forest_provider.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/routes/charts/charts.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/serializer/json_api_serializer.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/parser/validation.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/query.rb'
    - 'packages/forest_admin_datasource_active_record/spec/dummy/**/*'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/computed/utils/flattener.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/decorators_stack.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/publication/publication_collection_decorator.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/search/search_collection_decorator.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/write/write_replace/write_replace_collection_decorator.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/plugins/import_field.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/collection.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/condition_tree/condition_tree_factory.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/filter_factory.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/condition_tree/nodes/condition_tree_leaf.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/condition_tree/condition_tree_equivalent.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/validations/field_validator.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/actions/action_field_factory.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/base_action.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator.rb'

Metrics/BlockLength:
  Exclude:
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/filter_factory.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/action/base_action.rb'

Metrics/ClassLength:
  Exclude:
    - 'packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_field.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/services/permissions.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/routes/charts/charts.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/routes/action/actions.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/related/update_related.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/frontend_validation_utils.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/utils/query_string_parser.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/utils/query.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/collection_customizer.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/binary/binary_collection_decorator.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/search/search_collection_decorator.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/relation/relation_collection_decorator.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/rename_field/rename_field_collection_decorator.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/utils/collection.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/aggregation.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/filter_factory.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/condition_tree/nodes/condition_tree_leaf.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/condition_tree/transforms/comparisons.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/validations/rules.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/utils/schema/generator_action_field_widget.rb'
    - 'packages/forest_admin_datasource_active_record/lib/forest_admin_datasource_active_record/collection.rb'

Style/OpenStructUse:
  Exclude:
    - 'packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/**/*.rb'

RSpec/ExampleLength:
  CountAsOne: [ 'array', 'hash', 'method_call' ]
  Max: 20


RSpec/MultipleExpectations:
  Max: 10

Layout/LineLength:
  Max: 120
  Exclude:
    - 'packages/forest_admin_agent/spec/**/*'
    - 'packages/forest_admin_datasource_active_record/spec/**/*'
    - 'packages/forest_admin_datasource_toolkit/spec/**/*'
    - 'packages/forest_admin_datasource_customizer/spec/**/*'
    - 'packages/forest_admin_rails/spec/**/*'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/http/forest_admin_api_requester.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/routes/resources/list.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/services/permissions.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/override/context/create_override_customization_context.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/override/context/update_override_customization_context.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/override/context/delete_override_customization_context.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/publication/publication_datasource_decorator.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/relation/relation_collection_decorator.rb'
    - 'packages/forest_admin_datasource_customizer/lib/forest_admin_datasource_customizer/decorators/sort/sort_collection_decorator.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/condition_tree/condition_tree_factory.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/utils/collection.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/components/query/filter_factory.rb'
    - 'packages/forest_admin_datasource_toolkit/lib/forest_admin_datasource_toolkit/validations/field_validator.rb'

RSpec/MultipleMemoizedHelpers:
  Max: 10

Security/Eval:
  Exclude:
    - 'packages/forest_admin_agent/lib/forest_admin_agent/http/error_handling.rb'
    - 'packages/forest_admin_agent/lib/forest_admin_agent/services/logger_service.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'packages/forest_admin_rails/lib/generators/forest_admin_rails/install_generator.rb'

Lint/InterpolationCheck:
  Exclude:
    - 'packages/forest_admin_rails/lib/generators/forest_admin_rails/install_generator.rb'

Lint/UnusedMethodArgument:
  Exclude:
    - 'packages/forest_admin_rails/config/initializers/forest_admin_error_subscriber.rb'
