require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Gemspec/OrderedDependencies:
  Exclude:
    - 'packages/forestadmin_agent/forestadmin_agent.gemspec'
    - 'packages/forestadmin_rails/forestadmin_rails.gemspec'
    - 'forestadmin_rails.gemspec'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/PercentStringArray:
  Exclude:
    - 'packages/forestadmin_agent/forestadmin_agent.gemspec'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
RSpec/BeEq:
  Exclude:
    - 'spec/agent_ruby_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: be, be_nil
RSpec/BeNil:
  Exclude:
    - 'spec/agent_ruby_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
RSpec/ExpectActual:
  Exclude:
    - '**/spec/routing/**/*'
    - 'spec/agent_ruby_spec.rb'
    - 'packages/forestadmin_agent/spec/forestadmin_agent_spec.rb'
    - 'packages/forestadmin_rails/spec/forestadmin_rails_spec.rb'

# Offense count: 1
# Configuration parameters: AllowComments.
Lint/EmptyFile:
  Exclude:
    - 'packages/forestadmin_rails/app/models/forestadmin_rails/application_record.rb'

# Offense count: 3
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'packages/forestadmin_rails/app/helpers/forestadmin_rails/application_helper.rb'
    - 'packages/forestadmin_rails/lib/forestadmin_rails.rb'
    - 'packages/forestadmin_rails/lib/forestadmin_rails/engine.rb'

# Offense count: 9
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Exclude:
    - 'agent_ruby.gemspec'
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/console'
    - 'lib/agent_ruby.rb'
    - 'lib/agent_ruby/version.rb'
    - 'spec/agent_ruby_spec.rb'
    - 'spec/spec_helper.rb'
    - 'packages/forestadmin_agent/forestadmin_agent.gemspec'
    - 'packages/forestadmin_agent/Gemfile'
    - 'packages/forestadmin_agent/Rakefile'
    - 'packages/forestadmin_agent/bin/console'
    - packages/forestadmin_agent/lib/forestadmin_agent.rb
    - 'packages/forestadmin_agent/lib/forestadmin_agent/version.rb'
    - 'packages/forestadmin_agent/spec/forestadmin_agent_spec.rb'
    - 'packages/forestadmin_agent/spec/spec_helper.rb'
    - 'packages/forestadmin_rails/forestadmin_rails.gemspec'
    - 'packages/forestadmin_rails/Gemfile'
    - 'packages/forestadmin_rails/Rakefile'
    - 'packages/forestadmin_rails/bin/console'
    - 'packages/forestadmin_rails/lib/forestadmin_rails/version.rb'
    - 'packages/forestadmin_rails/spec/forestadmin_rails_spec.rb'
    - 'packages/forestadmin_rails/spec/spec_helper.rb'
    - 'packages/forestadmin_rails/bin/rails'
    - 'packages/forestadmin_rails/app/controllers/forestadmin_rails/application_controller.rb'
    - 'packages/forestadmin_rails/app/helpers/forestadmin_rails/application_helper.rb'
    - 'packages/forestadmin_rails/config/routes.rb'
    - 'packages/forestadmin_rails/lib/forestadmin_rails.rb'
    - 'packages/forestadmin_rails/lib/forestadmin_rails/engine.rb'
    - 'packages/forestadmin_rails/lib/forestadmin_rails/version.rb'
    - 'packages/forestadmin_rails/lib/tasks/forestadmin_rails_tasks.rake'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Exclude:
    - 'lib/agent_ruby/version.rb'
    - 'packages/forestadmin_agent/lib/forestadmin_agent/version.rb'
    - 'packages/forestadmin_rails/lib/forestadmin_rails/version.rb'

# Offense count: 38
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Exclude:
    - 'agent_ruby.gemspec'
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/console'
    - 'lib/agent_ruby.rb'
    - 'lib/agent_ruby/version.rb'
    - 'spec/agent_ruby_spec.rb'
    - 'spec/spec_helper.rb'
    - 'packages/forestadmin_agent/forestadmin_agent.gemspec'
    - 'packages/forestadmin_agent/Gemfile'
    - 'packages/forestadmin_agent/Rakefile'
    - 'packages/forestadmin_agent/bin/console'
    - 'packages/forestadmin_agent/lib/forestadmin_agent.rb'
    - 'packages/forestadmin_agent/lib/forestadmin_agent/version.rb'
    - 'packages/forestadmin_agent/spec/forestadmin_agent_spec.rb'
    - 'packages/forestadmin_agent/spec/spec_helper.rb'
    - 'packages/forestadmin_rails/forestadmin_rails.gemspec'
    - 'packages/forestadmin_rails/Gemfile'
    - 'packages/forestadmin_rails/Rakefile'
    - 'packages/forestadmin_rails/bin/console'
    - 'packages/forestadmin_rails/bin/rails'
    - 'packages/forestadmin_rails/lib/forestadmin_rails.rb'
    - 'packages/forestadmin_rails/lib/forestadmin_rails/version.rb'
    - 'packages/forestadmin_rails/spec/forestadmin_rails_spec.rb'
    - 'packages/forestadmin_rails/spec/spec_helper.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: percent
  MinSize: 3

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
