RSpec.shared_context :caller do
  let(:bearer) { 'Bearer eyJhbGciOiJIUzI1NiJ9.eyJpZCI6IjEiLCJlbWFpbCI6Im5pY29sYXNhQGZvcmVzdGFkbWluLmNvbSIsImZpcnN0X25hbWUiOiJOaWNvbGFzIiwibGFzdF9uYW1lIjoiQWxleGFuZHJlIiwidGVhbSI6Ik9wZXJhdGlvbnMiLCJ0YWdzIjpbXSwicmVuZGVyaW5nX2lkIjoxMTQsImV4cCI6MTY5NzAzNjQ0OSwicGVybWlzc2lvbl9sZXZlbCI6ImFkbWluIn0.UDUSshlxByL3kRjPMKK05Je3vTTKbDHqMtkqUBiwxDA' }
end
