require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

Gemspec/OrderedDependencies:
  Exclude:
    - 'forestadmin_rails.gemspec'

# Offense count: 1
# Configuration parameters: AllowComments.
Lint/EmptyFile:
  Exclude:
    - 'app/models/forestadmin_rails/application_record.rb'

# Offense count: 3
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/helpers/forestadmin_rails/application_helper.rb'
    - 'lib/forestadmin_rails.rb'
    - 'lib/forestadmin_rails/engine.rb'

# Offense count: 11
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'app/controllers/forestadmin_rails/application_controller.rb'
    - 'app/helpers/forestadmin_rails/application_helper.rb'
    - 'bin/rails'
    - 'config/routes.rb'
    - 'forestadmin_rails.gemspec'
    - 'lib/forestadmin_rails.rb'
    - 'lib/forestadmin_rails/engine.rb'
    - 'lib/forestadmin_rails/version.rb'
    - 'lib/tasks/forestadmin_rails_tasks.rake'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: literals, strict
Style/MutableConstant:
  Exclude:
    - 'lib/forestadmin_rails/version.rb'

# Offense count: 50
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, ConsistentQuotesInMultiline.
# SupportedStyles: single_quotes, double_quotes
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'bin/rails'
    - 'forestadmin_rails.gemspec'
    - 'lib/forestadmin_rails.rb'
    - 'lib/forestadmin_rails/version.rb'

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: MinSize, WordRegex.
# SupportedStyles: percent, brackets
Style/WordArray:
  EnforcedStyle: brackets

Layout/LineLength:
  Max: 120
