name: Build, Test and Deploy

on:
  push:
    branches:
      - main
      - beta
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']
        package:
          - forestadmin_agent
          - forestadmin_rails
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          ruby-version: ${{ matrix.ruby-version }}

      - name: Install dependencies on main repo
        run: |
          gem install bundler
          bundle install

      - name: Install dependencies on agent package
        working-directory: ./packages/forestadmin_agent
        run: bundle install

      - name: Install dependencies on plugin rails package
        working-directory: ./packages/forestadmin_rails
        run: bundle install

      - name: Run RuboCop
        run: bundle exec rubocop

      - name: Test
        run: cd packages/${{ matrix.package }} && bundle exec rspec && cd -

      - name: Send coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  deploy:
    name: Release package
    runs-on: ubuntu-latest

    needs: [test]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/beta')
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # GITHUB_TOKEN must not be set for the semantic release

      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.6

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install semantic release dependencies
        run: yarn

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17.3.0
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
