name: Notify CI Failure on Main

on:
  workflow_run:
    workflows: ['Lint, Test, Coverage and Deploy']
    types: [completed]
    branches: [main]

jobs:
  check-and-notify:
    uses: 'ForestAdmin/github-workflows/.github/workflows/notify-ci-failure.yml@main'
    secrets: inherit
